import os
import django


os.environ.setdefault(
    'DJANGO_SETTINGS_MODULE',
    'cyber_finance.settings'
)
django.setup()

from transactions.models import Account, Category, Tag, Transaction
from django.db.models import Count, Avg, Min, Max, Sum


print('--- START OF DJANGO ORM DEMO ---')


all_transactions = Transaction.objects.all()
print('\n1. All transactions in database:')
for t in all_transactions:
    print(f'  - {t}')


large_transactions = Transaction.objects.filter(amount__gt=500.00)
print('\n2. Transactions with amount greater than 500 UAH:')
for t in large_transactions:
    print(f'  - {t.account.name}: {t.transaction_type} of {t.amount} UAH')


cash_transactions = Transaction.objects.filter(account__name__iexact='Cash')
print('\n3. Filter by related model (Only Cash account transactions):')
for t in cash_transactions:
    print(f'  - {t}')


expenses_only = Transaction.objects.filter(transaction_type='expense')
print('\n4. Filter by choices field (Expenses only)):')
for t in expenses_only:
    print(f'  - Spent: {t.amount} UAH on category: {t.category.name if t.category else 'None'}')


top_3_largest = Transaction.objects.all().order_by('-amount')[:3]
print('\n5. Sorting + Limit (Top 3 largest financial operations):')
for i, t in enumerate(top_3_largest, 1):
    print(f'  {i}. {t.amount} UAH ({t.transaction_type}) - Account: {t.account.name}')


categories_with_count = Category.objects.annotate(total_tx=Count('transactions'))
print(f'\n6. Annotate (Count of transactions per category):')
for c in categories_with_count:
    print(f'  - Category "{c.name}" has {c.total_tx} transactions(s)')


custom_query = Transaction.objects.filter(transaction_type='expense')
print('\n7. Custom Query SQL Representation:')
print('  RAW SQL CODE GENERATED BY DJANGO ORM:')
print(f'  {custom_query.query}')

print('\n--- END OF DJANGO ORM DEMO ---')