# Generated by Django 6.1.1 on 2026-09-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Bank Card'), ('crypto', 'Crypto Wallet'), ('deposit', 'Deposit')], default='card', max_length=10, verbose_name='Account type'),
        ),
    ]
